repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer

-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        description: Format C code using clang-format.
        language: system
        files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
        entry: clang-format -i
        args: ["-style=Google"]

    -   id: cpplint
        name: cpplint
        description: Check style of C code using cpplint.
        language: python
        files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
        entry: cpplint
        args: ["--verbose=1", "--filter=-legal/copyright"]

    -   id: cppcheck
        name: cppcheck
        description: Check correctness of C code using cppcheck.
        language: system
        files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
        entry: cppcheck --error-exitcode=1
        args: ["--enable=warning"]
